### ISSUE TITLE
ДЗ1

### ISSUE THREAD

**Issue by katebogolepova** [Artem-Yakovlev/globus-first-homework#1]
Хорошо, очень лаконичное решение и с комментариями. Нужно подумать над случаем, когда человек хочет назвать слово целиком. Как можно иначе сделать вот это действие:         
for (int i = 0; i < words[random].length(); i++)
            secretWord.setCharAt(i, '*');

**Comment by Artem-Yakovlev** [comment]
Добавил возможность ввода слова целиком, а также изменил процесс заполнение слова символами "*"
